swagger: "2.0"
info:
  title: Cart API
  version: 1.0.0
host: localhost
basePath: /cart
schemes:
  - http
paths:
  /{username}:
    get:
      summary: Returns a cart for user.
      produces:
        - application/json
      parameters:
        - name: username
          in: path
          type: string
          required: true
          description: Username of user which cart should be shown
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Cart'

  /add:
    post:
      summary: Add product to cart
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CartItem'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Cart'
  /remove/{itemId}:
    delete:
      summary: Remove product from cart
      produces:
        - application/json
      parameters:
        - name: itemId
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Cart'

definitions:
  Cart:
    type: object
    properties:
      cartItem:
        type: array
        minimum: 0
        items:
          $ref: '#/definitions/CartItem'

  CartItem:
    type: object
    properties:
      id:
        type: integer
        format: int64
      count:
        type: integer
        format: int64
      product:
        type: object
        $ref: '#/definitions/Product'

  Product:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
        description: Name of the product
      amount:
        type: integer
        format: int64
        description: Amount of available product
      price:
        type: number
        format: double
        description: Price of the one product
