swagger: "2.0"
info:
  title: Product API
  version: 1.0.0
host: localhost
basePath: /product
schemes:
  - http
paths:
  /:
    post:
      summary: Add new product to the shop
      produces:
        - text/plain
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        200:
          description: Add new product
          schema:
            type: string
    put:
      summary: Update existing product
      produces:
        - text/plain
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        200:
          description: Update exist product
  /{productId}:
    get:
      summary: Get product by ID
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          required: true
          type: integer
          format: int64
          description: ID of product to return
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Product'
    delete:
      summary: Delete product by ID
      parameters:
        - name: productId
          in: path
          required: true
          type: integer
          format: int64
          description: ID of product to delete
      responses:
        200:
          description: successful opearion
  /all:
    get:
      summary: Get all products
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            $ref: '#/definitions/Product'

definitions:

  Product:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      amount:
        type: integer
        format: int64
      price:
        type: number
        format: double

